Repository HAK2024/fairy-share, pull requests merged in 2024-04, with the labels that each got.

#102 Feature/server/e3 expense tracking form
  server/src/app.module.ts
  server/src/expense/dto/create-expense-dto.ts
  server/src/expense/dto/index.ts
  server/src/expense/dto/update-expense-dto.ts
  server/src/expense/expense.controller.ts
  server/src/expense/expense.module.ts
  server/src/expense/expense.service.ts
  server/src/expense/test/expense.e2e-spec.ts
  server/src/payment/dto/index.ts
  server/src/payment/dto/update-payments-status-per-date-dto.ts
  server/src/payment/dto/update-payments-status-per-month-dto.ts
  server/src/payment/payment.controller.ts
  server/src/payment/payment.module.ts
  server/src/payment/payment.service.ts
  server/src/payment/test/payment.e2e-spec.ts
  server/src/prisma/seedData/expense.ts
  server/src/prisma/seedData/payment.ts
Labels: backend, Approved 🥳

#93 Feature/client/a5/members management modal
  client/app/_components/layout/container/FormContainer.tsx
  client/app/_hooks/useGetHouseInfo.ts
  client/app/_types/house.ts
  client/app/house/api/index.ts
  client/app/house/api/removeMemberApi.ts
  client/app/house/api/updateAdminApi.ts
  client/app/house/components/MembersManagement.tsx
  client/app/house/components/MembersManagementModal.tsx
  client/app/house/components/RemoveMemberAlertModal.tsx
  client/app/house/components/index.ts
  client/app/house/edit/page.tsx
  client/app/house/hooks/api/index.ts
  client/app/house/hooks/api/useRemoveMemberMutation.ts
  client/app/house/hooks/api/useUpdateAdminMutation.ts
  client/app/house/hooks/index.ts
  client/app/house/hooks/useRemoveMember.ts
  client/app/house/hooks/useUpdateAdmin.ts
  client/app/house/type/index.ts
  client/app/house/type/updateAdminType.ts
  client/package-lock.json
  client/package.json
  server/src/house/house.service.ts
  server/src/user/user.service.ts
Labels: frontend, backend, Approved 🥳

#104 feature/server/create get-expnese api
  server/src/expense/dto/get-expense-dto.ts
  server/src/expense/dto/index.ts
  server/src/expense/expense.controller.ts
  server/src/expense/expense.service.ts
  server/src/expense/test/expense.e2e-spec.ts
Labels: backend, Approved 🥳

#105 Feature/Server/Client/(Updated) U3 delete account
  client/app/_consts/path.ts
  client/app/account/api/deleteAccountApi.ts
  client/app/account/components/DeleteAccount.tsx
  client/app/account/hooks/api/useDeleteAccountMutation.ts
  client/app/account/hooks/useDeleteAccount.ts
  server/src/user/test/user.e2e-spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: frontend, backend, Approved 🥳

#108 feature/server/E4/create get-expense api
  server/src/expense/expense.controller.ts
  server/src/expense/expense.service.ts
  server/src/expense/test/expense.e2e-spec.ts
Labels: backend, Approved 🥳

#106 Feature/client/T1.Task Calendar
  client/.eslintrc.js
  client/.eslintrc.json
  client/app/_components/layout/SettingDropdown/SettingDropdown.tsx
  client/app/_components/layout/footer/Footer.tsx
  client/app/_consts/iconColor.ts
  client/app/_consts/index.ts
  client/app/_types/index.ts
  client/app/_types/task.ts
  client/app/house/hooks/api/useUpdateAdminMutation.ts
  client/app/house/hooks/useUpdateAdmin.ts
  client/app/page.tsx
  client/app/tasks/api/getTasksApi.ts
  client/app/tasks/api/index.ts
  client/app/tasks/components/TasksCalendar.tsx
  client/app/tasks/components/index.ts
  client/app/tasks/hooks/api/index.ts
  client/app/tasks/hooks/api/useGetTasksQuery.ts
  client/app/tasks/hooks/useCreateTask.ts
  client/app/tasks/hooks/useDeleteTask.ts
  client/app/tasks/page.tsx
  client/app/tasks/style/task-calendar.css
  client/package-lock.json
  client/package.json
  server/src/prisma/seedData/task.ts
  server/src/task/dto/get-tasks-query.dto.ts
  server/src/task/dto/index.ts
  server/src/task/task.controller.ts
  server/src/task/task.service.ts
  server/src/task/test/data/createTaskData.ts
  server/src/task/test/data/updateTaskData.ts
  server/src/task/test/task.e2e-spec.ts
Labels: frontend

#110 Feature/client/e4 update expense form
  client/app/(todos)/components/EmptyTask.tsx
  client/app/(todos)/components/TaskList.tsx
  client/app/(todos)/components/TodosList.tsx
  client/app/(todos)/components/index.tsx
  client/app/_components/layout/header/Header.tsx
  client/app/_types/expense.ts
  client/app/_types/index.ts
  client/app/expenses/[id]/edit/page.tsx
  client/app/expenses/api/getExpenseApi.ts
  client/app/expenses/api/index.ts
  client/app/expenses/api/updateExpenseApi.ts
  client/app/expenses/components/EditExpenseForm.tsx
  client/app/expenses/components/index.ts
  client/app/expenses/hooks/api/index.ts
  client/app/expenses/hooks/api/useGetExpenseQuery.ts
  client/app/expenses/hooks/api/useUpdateExpenseMutation.ts
  client/app/expenses/hooks/index.ts
  client/app/expenses/hooks/useCreateExpense.ts
  client/app/expenses/hooks/useUpdateExpense.ts
  client/app/expenses/page.tsx
  client/app/globals.css
Labels: frontend, Approved 🥳

#112 Update/Server/ Account Edit/ Email-validation
  server/src/user/user.service.ts
Labels: backend, Approved 🥳

#109 Feature/Client/U4 delete account warn admin
  client/app/_components/layout/SettingDropdown/SettingDropdown.tsx
  client/app/_consts/path.ts
  client/app/account/components/AccountInfo.tsx
  client/app/account/components/AdminWarningModal.tsx
  client/app/account/components/DeleteAccount.tsx
  client/app/account/components/DeleteAccountModal.tsx
  client/app/account/components/index.ts
  client/app/house/create/page.tsx
  client/app/house/edit/page.tsx
Labels: frontend, Approved 🥳

#113 Feature/client/e1 expense tracking per time
  client/app/_components/layout/footer/Footer.tsx
  client/app/_components/ui/Accordion.tsx
  client/app/_components/ui/button/Button.tsx
  client/app/_components/ui/index.ts
  client/app/_hooks/useGetHouseInfo.ts
  client/app/expenses/api/deleteExpenseApi.ts
  client/app/expenses/api/getExpensePerDateApi.ts
  client/app/expenses/api/index.ts
  client/app/expenses/api/updatePaymentStatusApi.ts
  client/app/expenses/components/DeleteExpense.tsx
  client/app/expenses/components/ExpenseItem.tsx
  client/app/expenses/components/ExpenseTrackingPerDate.tsx
  client/app/expenses/components/ExpenseTrackingPerMonth.tsx
  client/app/expenses/components/ItemDisplay.tsx
  client/app/expenses/components/PaymentItem.tsx
  client/app/expenses/components/UserDisplay.tsx
  client/app/expenses/components/index.ts
  client/app/expenses/hooks/api/index.ts
  client/app/expenses/hooks/api/useDeleteExpenseMutation.ts
  client/app/expenses/hooks/api/useGetExpensePerDateQuery.ts
  client/app/expenses/hooks/index.ts
  client/app/expenses/hooks/useDeleteExpense.ts
  client/app/expenses/hooks/useUpdateExpense.ts
  client/app/expenses/hooks/useUpdatePaymentStatus.ts
  client/app/expenses/page.tsx
  client/app/expenses/types/expenseTypePerDate.ts
  client/app/expenses/types/index.ts
  client/package-lock.json
  client/package.json
  server/src/expense/expense.controller.ts
  server/src/expense/expense.service.ts
  server/src/expense/test/expense.e2e-spec.ts
  server/src/house/house.service.ts
  server/src/payment/dto/update-payments-status-per-date-dto.ts
  server/src/payment/payment.controller.ts
  server/src/payment/payment.service.ts
  server/src/payment/test/payment.e2e-spec.ts
  server/src/prisma/seedData/expense.ts
  server/src/prisma/seedData/payment.ts
Labels: frontend, backend, Approved 🥳

#114 Feature/Client/T2. Task Calendar Modal
  client/app/_components/ui/Drawer.tsx
  client/app/_components/ui/dialog/Dialog.tsx
  client/app/_components/ui/index.ts
  client/app/_hooks/index.ts
  client/app/_hooks/useMediaQuery.ts
  client/app/account/hooks/useUpdateAccount.ts
  client/app/tasks/components/DeleteTaskModal.tsx
  client/app/tasks/components/TaskDetailsModal.tsx
  client/app/tasks/components/TasksCalendar.tsx
  client/app/tasks/components/index.ts
  client/app/tasks/hooks/api/useGetTaskQuery.ts
  client/app/tasks/hooks/index.ts
  client/app/tasks/hooks/useDeleteTask.ts
  client/app/tasks/hooks/useTaskDetailsModal.ts
  client/app/tasks/hooks/useUpdateTask.ts
  client/app/tasks/types/index.ts
  client/package-lock.json
  client/package.json
Labels: frontend, Approved 🥳

#118 Fix/Client/T2. Showing Task modal after a user delete the task
  client/app/tasks/components/DeleteTaskModal.tsx
Labels: frontend, Approved 🥳

#117 Feature/Server/Client/Change password
  client/app/_consts/path.ts
  client/app/account/api/changePasswordApi.ts
  client/app/account/api/index.ts
  client/app/account/api/updateAccountApi.ts
  client/app/account/change-password/page.tsx
  client/app/account/components/AccountInfo.tsx
  client/app/account/components/ChangePasswordForm.tsx
  client/app/account/components/index.ts
  client/app/account/hooks/api/index.ts
  client/app/account/hooks/api/useChangePasswordMutation.ts
  client/app/account/hooks/index.ts
  client/app/account/hooks/useChangePassword.ts
  client/app/account/schema/index.ts
  client/app/account/schema/password.ts
  server/src/user/dto/change-password-dto.ts
  server/src/user/dto/index.ts
  server/src/user/test/user.e2e-spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: frontend, backend, Review Required :eyes:

#119 Feature/client/e1 expense tracking per month
  client/app/account/edit/page.tsx
  client/app/account/hooks/useUpdateAccount.ts
  client/app/expenses/[id]/edit/page.tsx
  client/app/expenses/api/getExpensePerMonthApi.ts
  client/app/expenses/api/index.ts
  client/app/expenses/api/updatePaymentsStatusApi.ts
  client/app/expenses/components/ExpenseItem.tsx
  client/app/expenses/components/ExpenseTrackingPerDate.tsx
  client/app/expenses/components/ExpenseTrackingPerMonth.tsx
  client/app/expenses/components/ItemDisplayPerDate.tsx
  client/app/expenses/components/ItemDisplayPerMonth.tsx
  client/app/expenses/components/PaymentItem.tsx
  client/app/expenses/components/PaymentSummary.tsx
  client/app/expenses/components/UserDisplay.tsx
  client/app/expenses/components/UserExpenseItem.tsx
  client/app/expenses/components/index.ts
  client/app/expenses/hooks/api/index.ts
  client/app/expenses/hooks/api/useGetExpensePerDateQuery.ts
  client/app/expenses/hooks/api/useGetExpensePerMonthQuery.ts
  client/app/expenses/hooks/api/useGetExpenseQuery.ts
  client/app/expenses/hooks/api/useUpdatePaymentsStatusMutation.ts
  client/app/expenses/hooks/index.ts
  client/app/expenses/hooks/useCreateExpense.ts
  client/app/expenses/hooks/useDeleteExpense.ts
  client/app/expenses/hooks/useUpdateExpense.ts
  client/app/expenses/hooks/useUpdatePaymentStatus.ts
  client/app/expenses/hooks/useUpdatePaymentsStatus.ts
  client/app/expenses/types/expenseType.ts
  client/app/expenses/types/expenseTypePerDate.ts
  client/app/expenses/types/expenseTypePerMonth.ts
  client/app/expenses/types/index.ts
  client/app/expenses/types/updatePaymentsStatusType.ts
  client/app/house/hooks/useUpdateHouse.ts
  server/src/expense/expense.controller.ts
  server/src/expense/expense.service.ts
  server/src/expense/test/expense.e2e-spec.ts
Labels: frontend, backend

#122 Fix/Client/Task feature bugs
  client/app/(todos)/components/Alert.tsx
  client/app/(todos)/hooks/useUpdateStatusMutation.ts
  client/app/_components/layout/footer/Footer.tsx
  client/app/_components/ui/Badge.tsx
  client/app/_components/ui/index.ts
  client/app/account/hooks/useUpdateAccount.ts
  client/app/tasks/components/TaskDetailsModal.tsx
  client/app/tasks/style/task-calendar.css
  server/src/task/dto/create-task.dto.ts
  server/src/task/dto/update-task.dto.ts
  server/src/task/test/data/createTaskData.ts
  server/src/task/test/data/updateTaskData.ts
Labels: frontend, backend, Approved 🥳

#124 Fix/client/management modal member order&todos task hover style
  client/app/(todos)/components/TaskItem.tsx
  client/app/house/components/MembersManagementModal.tsx
Labels: frontend, Approved 🥳

#120 Fix/Client/update design
  client/app/_components/ui/link/RouterLink.tsx
  client/app/account/components/AccountInfo.tsx
  client/app/account/page.tsx
  client/app/expenses/page.tsx
  client/app/house/edit/page.tsx
  client/app/page.tsx
  client/app/tasks/page.tsx
Labels: frontend, Approved 🥳

#125 Fix/client/create-expnese-form
  client/app/expenses/components/CreateExpenseForm.tsx
  client/app/expenses/components/EditExpenseForm.tsx
  client/app/expenses/hooks/useCreateExpense.ts
Labels: frontend, Approved 🥳

#121 Refactor/Client/Refactor HouseInfo(rule) page
  client/app/_components/ui/heading/Heading.tsx
  client/app/house-info/component/HouseInfoList.tsx
  client/app/house-info/component/index.ts
  client/app/house-info/page.tsx
  client/app/page.tsx
  client/app/rules/component/RuleList.tsx
  client/app/rules/component/index.ts
Labels: frontend, Approved 🥳

#127 Fix/Client/Refactor-icons
  client/app/_components/layout/SettingDropdown/SettingDropdown.tsx
  client/app/_components/layout/footer/Footer.tsx
Labels: frontend, Approved 🥳

#126 Fix/Client/No.24 Expense Payment
  client/app/expenses/components/PaymentSummary.tsx
  client/app/expenses/components/UserExpenseItem.tsx
Labels: frontend, Approved 🥳

#128 Fix/client/expense form&change favicon
  client/app/expenses/components/ItemDisplayPerMonth.tsx
  client/app/favicon.ico
Labels: frontend, Approved 🥳

#131 Change/Client/House Form Label
  client/app/house/components/HouseCreateForm.tsx
  client/app/house/components/HouseUpdateForm.tsx
Labels: frontend, Approved 🥳

#132 fix URL
  server/src/libs/google-auth.ts
Labels: backend, Approved 🥳
