Repository HAK2024/fairy-share, pull requests merged in 2024-03, with the labels that each got.

#54 Feature/Server/A1-Auth
  .vscode/settings.json
  README.md
  server/.eslintrc.js
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/decorator/get-user.decorator.ts
  server/src/auth/decorator/index.ts
  server/src/auth/dto/index.ts
  server/src/auth/dto/login-dto.ts
  server/src/auth/dto/register-dto.ts
  server/src/auth/guard/auth.guard.ts
  server/src/auth/guard/index.ts
  server/src/auth/strategy/jwt.strategy.ts
  server/src/main.ts
  server/src/prisma/prisma.module.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend, Approved 🥳

#55 Feature/create common components
  client/.storybook/main.ts
  client/app/_components/layout/SettingDropdown/SettingDropdown.tsx
  client/app/_components/layout/SettingDropdown/stories/SettingDropdown.stories.ts
  client/app/_components/layout/footer/Footer.tsx
  client/app/_components/layout/footer/stories/Footer.stories.ts
  client/app/_components/layout/header/Header.tsx
  client/app/_components/layout/header/stories/Header.stories.ts
  client/app/_components/layout/index.ts
  client/app/_components/ui/button/Button.tsx
  client/app/_components/ui/dropdown/DropdownMenu.tsx
  client/app/_components/ui/heading/Heading.tsx
  client/app/_components/ui/heading/stories/Heading.stories.tsx
  client/app/_components/ui/index.ts
  client/app/layout.tsx
  client/app/page.tsx
  client/package-lock.json
  client/package.json
  client/public/images/logo/logo.png
  client/tailwind.config.ts
Labels: frontend, Approved 🥳

#58 Feature/change database schema
  server/erd.drawio
  server/src/auth/auth.service.ts
  server/src/auth/strategy/jwt.strategy.ts
  server/src/prisma/migrations/20240305092023_add_is_completed_to_tasks/migration.sql
  server/src/prisma/migrations/20240305094450_modify_column_name/migration.sql
  server/src/prisma/schema.prisma
  server/src/prisma/seedData/task.ts
  server/src/prisma/seedData/user.ts
  server/src/user/user.service.ts
Labels: documentation, backend, Approved 🥳

#56 Test/Feature/Server/A1-Auth
  .github/workflows/e2e-test.yml
  .github/workflows/lint.yml
  README.md
  server/.gitignore
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/src/app.controller.spec.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/login-dto.ts
  server/src/auth/dto/register-dto.ts
  server/src/auth/guard/auth.guard.ts
  server/src/auth/test/auth.e2e-spec.ts
  server/src/main.ts
  server/src/prisma/migrations/20240305213547_add_maximum_length_text/migration.sql
  server/src/prisma/prisma.service.ts
  server/src/prisma/schema.prisma
  server/src/user/test/user.e2e-spec.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
  server/test/app.e2e-spec.ts
  server/test/auth-set-tokens.ts
  server/test/build-default-modules.ts
  server/test/index.ts
  server/test/jest-e2e.json
Labels: backend

#59 Feature/change expense payment schema
  server/erd.drawio
  server/src/prisma/migrations/20240306001420_delete_expense_payments/migration.sql
  server/src/prisma/migrations/20240306004510_allow_null_to_paid_date_in_payment/migration.sql
  server/src/prisma/prisma.service.ts
  server/src/prisma/schema.prisma
  server/src/prisma/seed.ts
  server/src/prisma/seedData/expensePayment.ts
  server/src/prisma/seedData/index.ts
  server/src/prisma/seedData/payment.ts
Labels: documentation, backend, Approved 🥳

#65 Fix/server/GetMe API
  server/src/user/test/user.e2e-spec.ts
  server/src/user/user.service.ts
Labels: backend, Approved 🥳

#63 Feature/Client/A1-Login
  client/.eslintrc.json
  client/.gitignore
  client/app/(auth)/api/index.ts
  client/app/(auth)/api/loginApi.ts
  client/app/(auth)/components/LoginForm.tsx
  client/app/(auth)/components/index.ts
  client/app/(auth)/hooks/api/index.ts
  client/app/(auth)/hooks/api/useLoginMutation.ts
  client/app/(auth)/hooks/index.ts
  client/app/(auth)/hooks/useLogin.ts
  client/app/(auth)/login/page.tsx
  client/app/(auth)/register/page.tsx
  client/app/(auth)/schema/index.ts
  client/app/(auth)/schema/login.ts
  client/app/_api/base.ts
  client/app/_api/getCsrfTokenApi.ts
  client/app/_api/getMeApi.ts
  client/app/_api/index.ts
  client/app/_components/layout/footer/Footer.tsx
  client/app/_components/layout/header/Header.tsx
  client/app/_components/layout/header/stories/Header.stories.ts
  client/app/_components/layout/index.ts
  client/app/_components/layout/loading/Loading.tsx
  client/app/_components/ui/DropdownMenu.tsx
  client/app/_components/ui/Form.tsx
  client/app/_components/ui/Input.tsx
  client/app/_components/ui/Label.tsx
  client/app/_components/ui/Toast.tsx
  client/app/_components/ui/Toaster.tsx
  client/app/_components/ui/button/Button.tsx
  client/app/_components/ui/index.ts
  client/app/_components/ui/link/RouterLink.tsx
  client/app/_components/ui/link/stories/RouterLink.stories.ts
  client/app/_consts/iconColor.ts
  client/app/_consts/index.ts
  client/app/_consts/path.ts
  client/app/_hooks/api/index.ts
  client/app/_hooks/api/useGetCsrfTokenQuery.ts
  client/app/_hooks/api/useGetMeQuery.ts
  client/app/_hooks/index.ts
  client/app/_hooks/useToast.ts
  client/app/_providers/CheckAuth.tsx
  client/app/_providers/ClientComponents.tsx
  client/app/_providers/ReactQuery.tsx
  client/app/_providers/index.ts
  client/app/_store/auth.ts
  client/app/_store/index.ts
  client/app/_types/house.ts
  client/app/_types/index.ts
  client/app/_types/user.ts
  client/app/_utils/errorTypeGuard.ts
  client/app/_utils/index.ts
  client/app/_utils/shadcnUi.ts
  client/app/globals.css
  client/app/layout.tsx
  client/app/page.tsx
  client/components.json
  client/package-lock.json
  client/package.json
  client/tailwind.config.ts
Labels: frontend, Approved 🥳

#57 Feature/Server/M2-Rule
  server/package-lock.json
  server/src/house/house.controller.ts
  server/src/house/house.service.ts
  server/src/house/test/house.e2e-spec.ts
Labels: backend

#62 Feature/Client/M2-Rule
  client/app/_api/getHouseApi.ts
  client/app/_api/index.ts
  client/app/_hooks/api/index.ts
  client/app/_hooks/api/useGetHouseQuery.ts
  client/app/_stores/auth.ts
  client/app/_types/house.ts
  client/app/_types/index.ts
  client/app/_types/rules.ts
  client/app/_types/user.ts
  client/app/layout.tsx
  client/app/rules/component/RuleList.tsx
  client/app/rules/page.tsx
  server/src/house/house.service.ts
Labels: frontend, Approved 🥳

#69 Create/server/create task api
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/house/test/house.e2e-spec.ts
  server/src/task/dto/create-task.dto.ts
  server/src/task/dto/index.ts
  server/src/task/dto/update-task-status.dto.ts
  server/src/task/dto/update-task.dto.ts
  server/src/task/task.controller.ts
  server/src/task/task.module.ts
  server/src/task/task.service.ts
  server/src/task/test/data/createTaskData.ts
  server/src/task/test/data/index.ts
  server/src/task/test/data/updateTaskData.ts
  server/src/task/test/task.e2e-spec.ts
Labels: backend, Approved 🥳

#68 Feature/A1-Login&A2-Register/Google-auth
  client/app/(auth)/api/index.ts
  client/app/(auth)/api/loginGoogle.ts
  client/app/(auth)/components/LoginForm.tsx
  client/app/(auth)/components/RegisterForm.tsx
  client/app/(auth)/hooks/api/index.ts
  client/app/(auth)/hooks/api/useLoginGoogleMutation.ts
  client/app/(auth)/hooks/useLogin.ts
  client/app/_components/layout/SettingDropdown/SettingDropdown.tsx
  client/app/layout.tsx
  client/package-lock.json
  client/package.json
  server/package-lock.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.service.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/libs/google-auth.ts
  server/src/libs/index.ts
  server/src/prisma/migrations/20240311223150_change_hashed_password_to_nullable/migration.sql
  server/src/prisma/schema.prisma
Labels: frontend, backend, Approved 🥳

#72 create containr component
  client/app/_components/layout/container/FormContainer.tsx
  client/app/_components/layout/container/stories/FormContainer.stories.tsx
  client/app/_components/layout/index.ts
Labels: frontend, Approved 🥳

#70 Feature/Server/A4-House Setting
  .github/workflows/e2e-test.yml
  client/app/house/create/page.tsx
  server/erd.drawio
  server/package.json
  server/src/auth/test/auth.e2e-spec.ts
  server/src/house/dto/create-house-dto.ts
  server/src/house/dto/index.ts
  server/src/house/dto/sub-dto/create-rule-dto.ts
  server/src/house/dto/sub-dto/index.ts
  server/src/house/dto/sub-dto/update-rule-dto.ts
  server/src/house/dto/update-house-dto.ts
  server/src/house/house.controller.ts
  server/src/house/house.service.ts
  server/src/house/test/house.e2e-spec.ts
  server/src/prisma/migrations/20240312234719_add_cascade_for_house/migration.sql
  server/src/prisma/migrations/20240313013233_change_max_length_text/migration.sql
  server/src/prisma/schema.prisma
  server/src/prisma/seed.ts
  server/src/task/test/task.e2e-spec.ts
  server/src/user/test/user.e2e-spec.ts
  server/test/index.ts
  server/test/jest-e2e.json
  server/test/setup.ts
Labels: backend, Approved 🥳

#71 Feature/m1/client/create todos
  client/app/(todos)/components/Alert.tsx
  client/app/(todos)/components/EmptyTask.tsx
  client/app/(todos)/components/TaskItem.tsx
  client/app/(todos)/components/TaskList.tsx
  client/app/(todos)/components/TodosList.tsx
  client/app/(todos)/components/index.tsx
  client/app/(todos)/hooks/api/getTodosApi.ts
  client/app/(todos)/hooks/api/index.ts
  client/app/(todos)/hooks/api/updateTaskStatusApi.ts
  client/app/(todos)/hooks/index.ts
  client/app/(todos)/hooks/useGetTodosQuery.ts
  client/app/(todos)/hooks/useUpdateStatusMutation.ts
  client/app/_components/layout/footer/Footer.tsx
  client/app/_components/layout/header/Header.tsx
  client/app/_components/ui/checkbox/Checkbox.tsx
  client/app/_components/ui/checkbox/stories/Checkbox.stories.ts
  client/app/_components/ui/index.ts
  client/app/_providers/CheckAuth.tsx
  client/app/_types/index.ts
  client/app/_types/task.ts
  client/app/_types/todo.ts
  client/app/globals.css
  client/app/layout.tsx
  client/app/page.tsx
  client/package-lock.json
  client/package.json
  client/tailwind.config.ts
  server/src/house/house.service.ts
Labels: frontend, Approved 🥳

#73 Feature/Client/U1 account
  client/app/_components/layout/SettingDropdown/SettingDropdown.tsx
  client/app/_components/layout/container/FormContainer.tsx
  client/app/_components/layout/container/stories/FormContainer.stories.tsx
  client/app/_components/ui/heading/Heading.tsx
  client/app/_components/ui/heading/stories/Heading.stories.tsx
  client/app/_consts/iconColor.ts
  client/app/_consts/index.ts
  client/app/account/component/AccountInfo.tsx
  client/app/account/component/index.ts
  client/app/account/page.tsx
  client/app/page.tsx
  client/app/rules/component/RuleList.tsx
  client/app/rules/component/index.ts
  client/app/rules/page.tsx
Labels: frontend

#76 Feature/Register,Login using Invitation Code
  client/.storybook/preview.ts
  client/.storybook/preview.tsx
  client/app/(auth)/api/loginApi.ts
  client/app/(auth)/api/loginGoogle.ts
  client/app/(auth)/api/registerApi.ts
  client/app/(auth)/components/LoginForm.tsx
  client/app/(auth)/components/RegisterForm.tsx
  client/app/(auth)/hooks/api/useLoginGoogleMutation.ts
  client/app/(auth)/hooks/api/useLoginMutation.ts
  client/app/(auth)/hooks/api/useRegisterMutation.ts
  client/app/(auth)/hooks/useLogin.ts
  client/app/(auth)/hooks/useRegister.ts
  client/app/(auth)/login/page.tsx
  client/app/(auth)/register/page.tsx
  client/app/(todos)/hooks/useGetTodosQuery.ts
  client/app/(todos)/hooks/useUpdateStatusMutation.ts
  client/app/_api/createUserHouseApi.ts
  client/app/_api/index.ts
  client/app/_components/layout/SettingDropdown/SettingDropdown.tsx
  client/app/_components/layout/header/Header.tsx
  client/app/_components/layout/loading/stories/loading.stories.ts
  client/app/_components/ui/Dialog.tsx
  client/app/_components/ui/Toaster.tsx
  client/app/_components/ui/dialog/InvitedHouseAlertDialog.tsx
  client/app/_components/ui/index.ts
  client/app/_consts/index.ts
  client/app/_consts/params.ts
  client/app/_consts/path.ts
  client/app/_hooks/api/index.ts
  client/app/_hooks/api/useCreateUserHouseMutation.ts
  client/app/_hooks/api/useGetHouseQuery.ts
  client/app/_hooks/api/useGetMeQuery.ts
  client/app/_hooks/index.ts
  client/app/_hooks/useCheckInvitedHouse.ts
  client/app/_hooks/useGetHouseId.ts
  client/app/_providers/CheckAuth.tsx
  client/app/_stores/auth.ts
  client/app/_types/index.ts
  client/app/_types/userHouse.ts
  client/app/house/create/page.tsx
  client/app/layout.tsx
  client/app/page.tsx
  client/app/rules/page.tsx
  client/package-lock.json
  client/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/auth-query-dto.ts
  server/src/auth/dto/index.ts
  server/src/auth/test/auth.e2e-spec.ts
  server/src/house/house.service.ts
  server/src/user-house/dto/create-user-house.dto.ts
  server/src/user-house/dto/index.ts
  server/src/user-house/test/user-house.e2e-spec.ts
  server/src/user-house/user-house.controller.ts
  server/src/user-house/user-house.module.ts
  server/src/user-house/user-house.service.ts
Labels: frontend, backend, Approved 🥳

#80 Feature/client/t3 create task
  client/app/(todos)/api/getTodosApi.ts
  client/app/(todos)/api/index.ts
  client/app/(todos)/api/updateTaskStatusApi.ts
  client/app/(todos)/hooks/useGetTodosQuery.ts
  client/app/(todos)/hooks/useUpdateStatusMutation.ts
  client/app/_components/layout/container/FormContainer.tsx
  client/app/_components/ui/CustomDayPicker.tsx
  client/app/_components/ui/Popover.tsx
  client/app/_components/ui/Textarea.tsx
  client/app/_components/ui/button/Button.tsx
  client/app/_components/ui/field/DateField.tsx
  client/app/_components/ui/field/stories/DateFeild.stories.tsx
  client/app/_components/ui/index.ts
  client/app/_consts/iconColor.ts
  client/app/_providers/CheckAuth.tsx
  client/app/_types/house.ts
  client/app/_types/user.ts
  client/app/tasks/[id]/edit/page.tsx
  client/app/tasks/api/createTaskApi.ts
  client/app/tasks/api/index.ts
  client/app/tasks/components/AssigneeField.tsx
  client/app/tasks/components/CreateTaskForm.tsx
  client/app/tasks/components/index.ts
  client/app/tasks/create/page.tsx
  client/app/tasks/hooks/api/index.ts
  client/app/tasks/hooks/api/useCreateTaskMutation.ts
  client/app/tasks/hooks/index.ts
  client/app/tasks/hooks/useCreateTask.ts
  client/app/tasks/page.tsx
  client/app/tasks/schema/index.ts
  client/app/tasks/schema/task.ts
  client/package-lock.json
  client/package.json
  server/src/house/house.service.ts
  server/src/user/user.service.ts
Labels: frontend, backend, Approved 🥳

#81 Feature/client/A3 House Setting (Create)
  client/app/_components/ui/Form.tsx
  client/app/_components/ui/RadioGroup.tsx
  client/app/_components/ui/Toaster.tsx
  client/app/_components/ui/dialog/Dialog.tsx
  client/app/_components/ui/dialog/InvitedHouseAlertDialog.tsx
  client/app/_components/ui/index.ts
  client/app/_components/ui/input/Input.tsx
  client/app/_hooks/api/useCreateUserHouseMutation.ts
  client/app/house/api/createHouseApi.ts
  client/app/house/api/index.ts
  client/app/house/components/DynamicRuleField.tsx
  client/app/house/components/HouseCreateForm.tsx
  client/app/house/components/index.ts
  client/app/house/create/page.tsx
  client/app/house/hooks/api/index.ts
  client/app/house/hooks/api/useCreateHouseMutation.ts
  client/app/house/hooks/useCreateHouse.ts
  client/app/house/schema/createHouse.ts
  client/app/house/schema/index.ts
  client/app/tasks/components/CreateTaskForm.tsx
  client/package-lock.json
  client/package.json
Labels: frontend, Approved 🥳

#86 feature/client/T5-delete-task
  client/app/tasks/api/deleteTaskApi.ts
  client/app/tasks/api/index.ts
  client/app/tasks/hooks/api/index.ts
  client/app/tasks/hooks/api/useDeleteTaskMutation.ts
  client/app/tasks/hooks/index.ts
  client/app/tasks/hooks/useDeleteTask.ts
  client/app/tasks/page.tsx
Labels: frontend, Approved 🥳

#85 Feature/Client/U2 account edit
  client/app/(auth)/api/index.ts
  client/app/(auth)/hooks/api/index.ts
  client/app/(auth)/schema/index.ts
  client/app/_consts/iconColor.ts
  client/app/_types/index.ts
  client/app/account/api/accountUpdateApi.ts
  client/app/account/api/index.ts
  client/app/account/component/index.ts
  client/app/account/components/AccountInfo.tsx
  client/app/account/components/EditAccountForm.tsx
  client/app/account/components/index.ts
  client/app/account/edit/page.tsx
  client/app/account/hooks/api/index.ts
  client/app/account/hooks/api/useAccountMutation.ts
  client/app/account/hooks/index.ts
  client/app/account/hooks/useAccountEdit.ts
  client/app/account/page.tsx
  client/app/account/schema/account.ts
  client/app/account/schema/index.ts
Labels: frontend, Approved 🥳

#88 Feature/Client/A4 House Setting Delete
  client/app/_components/ui/dialog/AlertDialog.tsx
  client/app/_components/ui/dialog/stories/AlertDialog.stories.tsx
  client/app/_components/ui/index.ts
  client/app/house/api/deleteHouseApi.ts
  client/app/house/api/index.ts
  client/app/house/components/DeleteHouse.tsx
  client/app/house/components/index.ts
  client/app/house/edit/page.tsx
  client/app/house/hooks/api/index.ts
  client/app/house/hooks/api/useDeleteHouseMutation.ts
  client/app/house/hooks/index.ts
  client/app/house/hooks/useDeleteHouse.ts
  client/package-lock.json
  client/package.json
Labels: frontend, Approved 🥳

#89 Feature/Client/Error Handling （Query & Component)
  client/app/(todos)/hooks/useGetTodosQuery.ts
  client/app/_hooks/api/useCreateUserHouseMutation.ts
  client/app/_hooks/api/useGetCsrfTokenQuery.ts
  client/app/_hooks/api/useGetHouseQuery.ts
  client/app/_hooks/api/useGetMeQuery.ts
  client/app/account/components/AccountInfo.tsx
  client/app/error.tsx
  client/app/global-error.tsx
  client/app/house/create/page.tsx
  client/app/house/hooks/index.ts
  client/app/house/hooks/useCreateUserHouseOnMount.ts
  client/app/not-found.tsx
  client/app/page.tsx
  client/app/rules/page.tsx
  client/app/tasks/[id]/edit/page.tsx
  client/app/tasks/hooks/api/useGetTaskQuery.ts
Labels: frontend, Approved 🥳

#77 Feature/Server(Client)/U2-Account Edit
  client/app/account/api/accountUpdateApi.ts
  client/app/account/api/index.ts
  client/app/account/api/updateAccountApi.ts
  client/app/account/components/AccountInfo.tsx
  client/app/account/components/UpdateAccountForm.tsx
  client/app/account/components/index.ts
  client/app/account/edit/page.tsx
  client/app/account/hooks/api/index.ts
  client/app/account/hooks/api/useUpdateAccountMutation.ts
  client/app/account/hooks/index.ts
  client/app/account/hooks/useUpdateAccount.ts
  client/app/account/page.tsx
  server/src/auth/auth.module.ts
  server/src/user/dto/update-user-dto.ts
  server/src/user/test/user.e2e-spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend, Approved 🥳

#92 Refactor/Client/Name Consistency for Edit Update
  client/app/account/hooks/useUpdateAccount.ts
  client/app/tasks/api/index.ts
  client/app/tasks/api/updateTaskApi.ts
  client/app/tasks/components/EditTaskForm.tsx
  client/app/tasks/hooks/api/index.ts
  client/app/tasks/hooks/api/useUpdateTaskMutation.ts
  client/app/tasks/hooks/index.ts
  client/app/tasks/hooks/useUpdateTask.ts
Labels: frontend, Approved 🥳

#90 Feature/server/a5/members management modal
  server/src/prisma/seedData/userHouse.ts
  server/src/user-house/dto/delete-user-house.dto.ts
  server/src/user-house/dto/index.ts
  server/src/user-house/dto/update-admin.dto.ts
  server/src/user-house/test/user-house.e2e-spec.ts
  server/src/user-house/user-house.controller.ts
  server/src/user-house/user-house.service.ts
Labels: backend, Approved 🥳

#91 Feature/Server/T1. Task Calendar
  client/app/tasks/api/createTaskApi.ts
  server/src/task/task.controller.ts
  server/src/task/task.service.ts
  server/src/task/test/task.e2e-spec.ts
Labels: backend, Approved 🥳
